vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        update_file:
            uri_prefix: /update/files
            upload_destination: '%kernel.project_dir%/../public_html/update/files'
            namer: App\Naming\OriginalNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_property:  created
                    date_time_format: 'Y/m/d/His' # will create directory "2018/23/09" for curent date "2018-09-23"
        divers_file:
            uri_prefix: /fichiers
            upload_destination: '%kernel.project_dir%/../public_html/fichiers'
            namer: App\Naming\OriginalNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_property:  created
                    date_time_format: 'Y/m/d/His' # will create directory "2018/23/09" for curent date "2018-09-23"